#!/bin/python3

import math
import os
import random
import re
import sys



if __name__ == '__main__':
    
    #taking input from the user
    n = int(input().strip())
    
    #let check ifthe number is between 1 and 100
    if n>=1 and n<=100:
    
        # if the number 'n' leaves the reminder 1 , its odd
        if n % 2 == 1 :
            print('Weird')
        else:
            # even + between 2 and 5
            if n >=2 and n <=5:
                print('Not Weird')
                
            # even + between 6 and 20
            elif n >=6 and n <=20:
                print('Weird')
            
            # even and > 20
            elif n >20:
                print('Not Weird')
